/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jubio_Jubio */

#ifndef _Included_jubio_Jubio
#define _Included_jubio_Jubio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jubio_Jubio
 * Method:    _load
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jubio_Jubio__1load
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     jubio_Jubio
 * Method:    _unload
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jubio_Jubio__1unload
  (JNIEnv *, jclass, jint);

/*
 * Class:     jubio_Jubio
 * Method:    _getWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jubio_Jubio__1getWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     jubio_Jubio
 * Method:    _getHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jubio_Jubio__1getHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     jubio_Jubio
 * Method:    _getDepth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jubio_Jubio__1getDepth
  (JNIEnv *, jclass, jint);

/*
 * Class:     jubio_Jubio
 * Method:    _calcMax
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jubio_Jubio__1calcMax
  (JNIEnv *, jclass, jint);

/*
 * Class:     jubio_Jubio
 * Method:    _getDataArray
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jubio_Jubio__1getDataArray
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
