/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package evplugin.script.parser;

public interface ParserConstants {

  int EOF = 0;
  int SYM = 5;
  int STRING = 6;
  int INFIX = 7;
  int INTEGER = 8;
  int REAL = 9;
  int OPEN_PAR = 10;
  int CLOSE_PAR = 11;
  int OPEN_LIST = 12;
  int CLOSE_LIST = 13;
  int COMMA = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<SYM>",
    "<STRING>",
    "<INFIX>",
    "<INTEGER>",
    "<REAL>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
