all:
	gcc -g vectoradd.cpp -I/usr/lib/jvm/java-6-openjdk/include/ -I ./include -I ~/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ -L /home/mahogny/NVIDIA_GPU_Computing_SDK/OpenCL/common/lib/Linux32/ -lOpenCL
