/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qhull_QHull */

#ifndef _Included_qhull_QHull
#define _Included_qhull_QHull
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qhull_QHull
 * Method:    voronoi_
 * Signature: (Lqhull/VoronoiResult;[Ljavax/vecmath/Vector3d;)Z
 */
JNIEXPORT jboolean JNICALL Java_qhull_QHull_voronoi_1
  (JNIEnv *, jclass, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
