/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdlib.h>
#include <stddef.h>
#include <string.h>
//#include <CL/cl.h>
#include "include/cl_platform.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_opencl_RawOpenCLJNI_cl_1image_1format_1image_1channel_1order_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  cl_image_format *arg1 = (cl_image_format *) 0 ;
  cl_channel_order arg2 ;
  cl_channel_order *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(cl_image_format **)&jarg1; 
  argp2 = *(cl_channel_order **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_channel_order");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->image_channel_order = arg2;
  
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_cl_1image_1format_1image_1channel_1order_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  cl_image_format *arg1 = (cl_image_format *) 0 ;
  cl_channel_order result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(cl_image_format **)&jarg1; 
  result =  ((arg1)->image_channel_order);
  {
    cl_channel_order * resultptr = (cl_channel_order *) malloc(sizeof(cl_channel_order));
    memmove(resultptr, &result, sizeof(cl_channel_order));
    *(cl_channel_order **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_opencl_RawOpenCLJNI_cl_1image_1format_1image_1channel_1data_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  cl_image_format *arg1 = (cl_image_format *) 0 ;
  cl_channel_type arg2 ;
  cl_channel_type *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(cl_image_format **)&jarg1; 
  argp2 = *(cl_channel_type **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_channel_type");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->image_channel_data_type = arg2;
  
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_cl_1image_1format_1image_1channel_1data_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  cl_image_format *arg1 = (cl_image_format *) 0 ;
  cl_channel_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(cl_image_format **)&jarg1; 
  result =  ((arg1)->image_channel_data_type);
  {
    cl_channel_type * resultptr = (cl_channel_type *) malloc(sizeof(cl_channel_type));
    memmove(resultptr, &result, sizeof(cl_channel_type));
    *(cl_channel_type **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_new_1cl_1image_1format(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  cl_image_format *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (cl_image_format *)(cl_image_format *) calloc(1, sizeof(cl_image_format));
  *(cl_image_format **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_opencl_RawOpenCLJNI_delete_1cl_1image_1format(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  cl_image_format *arg1 = (cl_image_format *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_image_format **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetPlatformIDs(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  cl_uint arg1 ;
  cl_platform_id *arg2 = (cl_platform_id *) 0 ;
  cl_uint *arg3 = (cl_uint *) 0 ;
  cl_int result;
  cl_uint *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(cl_uint **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(cl_platform_id **)&jarg2; 
  arg3 = *(cl_uint **)&jarg3; 
  result = clGetPlatformIDs(arg1,arg2,arg3);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetPlatformInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_platform_id arg1 = (cl_platform_id) 0 ;
  cl_platform_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_platform_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_platform_id *)&jarg1; 
  argp2 = *(cl_platform_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_platform_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetPlatformInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetDeviceIDs(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_platform_id arg1 = (cl_platform_id) 0 ;
  cl_device_type arg2 ;
  cl_uint arg3 ;
  cl_device_id *arg4 = (cl_device_id *) 0 ;
  cl_uint *arg5 = (cl_uint *) 0 ;
  cl_int result;
  cl_uint *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_platform_id *)&jarg1; 
  arg2 = (cl_device_type)jarg2; 
  argp3 = *(cl_uint **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(cl_device_id **)&jarg4; 
  arg5 = *(cl_uint **)&jarg5; 
  result = clGetDeviceIDs(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetDeviceInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_device_id arg1 = (cl_device_id) 0 ;
  cl_device_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_device_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_device_id *)&jarg1; 
  argp2 = *(cl_device_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_device_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetDeviceInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateContext(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  cl_context_properties *arg1 = (cl_context_properties *) 0 ;
  cl_uint arg2 ;
  cl_device_id *arg3 = (cl_device_id *) 0 ;
  void (*arg4)(char const *,void const *,size_t,void *) = (void (*)(char const *,void const *,size_t,void *)) 0 ;
  void *arg5 = (void *) 0 ;
  cl_int *arg6 = (cl_int *) 0 ;
  cl_context result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context_properties **)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(cl_device_id **)&jarg3; 
  arg4 = *(void (**)(char const *,void const *,size_t,void *))&jarg4; 
  arg5 = *(void **)&jarg5; 
  arg6 = *(cl_int **)&jarg6; 
  result = (cl_context)clCreateContext(arg1,arg2,(void *const *)arg3,arg4,arg5,arg6);
  *(cl_context *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateContextFromType(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_context_properties *arg1 = (cl_context_properties *) 0 ;
  cl_device_type arg2 ;
  void (*arg3)(char const *,void const *,size_t,void *) = (void (*)(char const *,void const *,size_t,void *)) 0 ;
  void *arg4 = (void *) 0 ;
  cl_int *arg5 = (cl_int *) 0 ;
  cl_context result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context_properties **)&jarg1; 
  arg2 = (cl_device_type)jarg2; 
  arg3 = *(void (**)(char const *,void const *,size_t,void *))&jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(cl_int **)&jarg5; 
  result = (cl_context)clCreateContextFromType(arg1,arg2,arg3,arg4,arg5);
  *(cl_context *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainContext(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  result = clRetainContext(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseContext(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  result = clReleaseContext(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetContextInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_context_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_context_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  argp2 = *(cl_context_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_context_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetContextInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateCommandQueue(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_device_id arg2 = (cl_device_id) 0 ;
  cl_command_queue_properties arg3 ;
  cl_int *arg4 = (cl_int *) 0 ;
  cl_command_queue result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  arg2 = *(cl_device_id *)&jarg2; 
  arg3 = (cl_command_queue_properties)jarg3; 
  arg4 = *(cl_int **)&jarg4; 
  result = (cl_command_queue)clCreateCommandQueue(arg1,arg2,arg3,arg4);
  *(cl_command_queue *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainCommandQueue(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  result = clRetainCommandQueue(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseCommandQueue(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  result = clReleaseCommandQueue(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetCommandQueueInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_command_queue_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_command_queue_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  argp2 = *(cl_command_queue_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_command_queue_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetCommandQueueInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clSetCommandQueueProperty(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_command_queue_properties arg2 ;
  cl_bool arg3 ;
  cl_command_queue_properties *arg4 = (cl_command_queue_properties *) 0 ;
  cl_int result;
  cl_bool *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = (cl_command_queue_properties)jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(cl_command_queue_properties **)&jarg4; 
  result = clSetCommandQueueProperty(arg1,arg2,arg3,arg4);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_mem_flags arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  cl_int *arg5 = (cl_int *) 0 ;
  cl_mem result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  arg2 = (cl_mem_flags)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(cl_int **)&jarg5; 
  result = (cl_mem)clCreateBuffer(arg1,arg2,arg3,arg4,arg5);
  *(cl_mem *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateImage2D(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_mem_flags arg2 ;
  cl_image_format *arg3 = (cl_image_format *) 0 ;
  size_t arg4 ;
  size_t arg5 ;
  size_t arg6 ;
  void *arg7 = (void *) 0 ;
  cl_int *arg8 = (cl_int *) 0 ;
  cl_mem result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(cl_context *)&jarg1; 
  arg2 = (cl_mem_flags)jarg2; 
  arg3 = *(cl_image_format **)&jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = (size_t)jarg6; 
  arg7 = *(void **)&jarg7; 
  arg8 = *(cl_int **)&jarg8; 
  result = (cl_mem)clCreateImage2D(arg1,arg2,(struct _cl_image_format const *)arg3,arg4,arg5,arg6,arg7,arg8);
  *(cl_mem *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateImage3D(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_mem_flags arg2 ;
  cl_image_format *arg3 = (cl_image_format *) 0 ;
  size_t arg4 ;
  size_t arg5 ;
  size_t arg6 ;
  size_t arg7 ;
  size_t arg8 ;
  void *arg9 = (void *) 0 ;
  cl_int *arg10 = (cl_int *) 0 ;
  cl_mem result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(cl_context *)&jarg1; 
  arg2 = (cl_mem_flags)jarg2; 
  arg3 = *(cl_image_format **)&jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = (size_t)jarg6; 
  arg7 = (size_t)jarg7; 
  arg8 = (size_t)jarg8; 
  arg9 = *(void **)&jarg9; 
  arg10 = *(cl_int **)&jarg10; 
  result = (cl_mem)clCreateImage3D(arg1,arg2,(struct _cl_image_format const *)arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  *(cl_mem *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainMemObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_mem arg1 = (cl_mem) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_mem *)&jarg1; 
  result = clRetainMemObject(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseMemObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_mem arg1 = (cl_mem) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_mem *)&jarg1; 
  result = clReleaseMemObject(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetSupportedImageFormats(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jobject jarg5_, jlong jarg6) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_mem_flags arg2 ;
  cl_mem_object_type arg3 ;
  cl_uint arg4 ;
  cl_image_format *arg5 = (cl_image_format *) 0 ;
  cl_uint *arg6 = (cl_uint *) 0 ;
  cl_int result;
  cl_mem_object_type *argp3 ;
  cl_uint *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(cl_context *)&jarg1; 
  arg2 = (cl_mem_flags)jarg2; 
  argp3 = *(cl_mem_object_type **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_mem_object_type");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(cl_uint **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(cl_image_format **)&jarg5; 
  arg6 = *(cl_uint **)&jarg6; 
  result = clGetSupportedImageFormats(arg1,arg2,arg3,arg4,arg5,arg6);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetMemObjectInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_mem arg1 = (cl_mem) 0 ;
  cl_mem_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_mem_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_mem *)&jarg1; 
  argp2 = *(cl_mem_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_mem_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetMemObjectInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetImageInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_mem arg1 = (cl_mem) 0 ;
  cl_image_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_image_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_mem *)&jarg1; 
  argp2 = *(cl_image_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_image_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetImageInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateSampler(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_bool arg2 ;
  cl_addressing_mode arg3 ;
  cl_filter_mode arg4 ;
  cl_int *arg5 = (cl_int *) 0 ;
  cl_sampler result;
  cl_bool *argp2 ;
  cl_addressing_mode *argp3 ;
  cl_filter_mode *argp4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  argp2 = *(cl_bool **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(cl_addressing_mode **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_addressing_mode");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(cl_filter_mode **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_filter_mode");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(cl_int **)&jarg5; 
  result = (cl_sampler)clCreateSampler(arg1,arg2,arg3,arg4,arg5);
  *(cl_sampler *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainSampler(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_sampler arg1 = (cl_sampler) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_sampler *)&jarg1; 
  result = clRetainSampler(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseSampler(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_sampler arg1 = (cl_sampler) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_sampler *)&jarg1; 
  result = clReleaseSampler(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetSamplerInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_sampler arg1 = (cl_sampler) 0 ;
  cl_sampler_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_sampler_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_sampler *)&jarg1; 
  argp2 = *(cl_sampler_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_sampler_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetSamplerInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateProgramWithSource(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_uint arg2 ;
  char **arg3 = (char **) 0 ;
  size_t *arg4 = (size_t *) 0 ;
  cl_int *arg5 = (cl_int *) 0 ;
  cl_program result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(char ***)&jarg3; 
  arg4 = *(size_t **)&jarg4; 
  arg5 = *(cl_int **)&jarg5; 
  result = (cl_program)clCreateProgramWithSource(arg1,arg2,(char const **)arg3,(size_t const *)arg4,arg5);
  *(cl_program *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateProgramWithBinary(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7) {
  jlong jresult = 0 ;
  cl_context arg1 = (cl_context) 0 ;
  cl_uint arg2 ;
  cl_device_id *arg3 = (cl_device_id *) 0 ;
  size_t *arg4 = (size_t *) 0 ;
  unsigned char **arg5 = (unsigned char **) 0 ;
  cl_int *arg6 = (cl_int *) 0 ;
  cl_int *arg7 = (cl_int *) 0 ;
  cl_program result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_context *)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(cl_device_id **)&jarg3; 
  arg4 = *(size_t **)&jarg4; 
  arg5 = *(unsigned char ***)&jarg5; 
  arg6 = *(cl_int **)&jarg6; 
  arg7 = *(cl_int **)&jarg7; 
  result = (cl_program)clCreateProgramWithBinary(arg1,arg2,(void *const *)arg3,(size_t const *)arg4,(unsigned char const **)arg5,arg6,arg7);
  *(cl_program *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainProgram(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  result = clRetainProgram(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseProgram(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  result = clReleaseProgram(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clBuildProgram(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jstring jarg4, jlong jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  cl_uint arg2 ;
  cl_device_id *arg3 = (cl_device_id *) 0 ;
  char *arg4 = (char *) 0 ;
  void (*arg5)(cl_program,void *) = (void (*)(cl_program,void *)) 0 ;
  void *arg6 = (void *) 0 ;
  cl_int result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(cl_device_id **)&jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = *(void (**)(cl_program,void *))&jarg5; 
  arg6 = *(void **)&jarg6; 
  result = clBuildProgram(arg1,arg2,(void *const *)arg3,(char const *)arg4,arg5,arg6);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clUnloadCompiler(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  result = clUnloadCompiler();
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetProgramInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  cl_program_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_program_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  argp2 = *(cl_program_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_program_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetProgramInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetProgramBuildInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  cl_device_id arg2 = (cl_device_id) 0 ;
  cl_program_build_info arg3 ;
  size_t arg4 ;
  void *arg5 = (void *) 0 ;
  size_t *arg6 = (size_t *) 0 ;
  cl_int result;
  cl_program_build_info *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  arg2 = *(cl_device_id *)&jarg2; 
  argp3 = *(cl_program_build_info **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_program_build_info");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (size_t)jarg4; 
  arg5 = *(void **)&jarg5; 
  arg6 = *(size_t **)&jarg6; 
  result = clGetProgramBuildInfo(arg1,arg2,arg3,arg4,arg5,arg6);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateKernel(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  char *arg2 = (char *) 0 ;
  cl_int *arg3 = (cl_int *) 0 ;
  cl_kernel result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(cl_int **)&jarg3; 
  result = (cl_kernel)clCreateKernel(arg1,(char const *)arg2,arg3);
  *(cl_kernel *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clCreateKernelsInProgram(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  cl_program arg1 = (cl_program) 0 ;
  cl_uint arg2 ;
  cl_kernel *arg3 = (cl_kernel *) 0 ;
  cl_uint *arg4 = (cl_uint *) 0 ;
  cl_int result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_program *)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(cl_kernel **)&jarg3; 
  arg4 = *(cl_uint **)&jarg4; 
  result = clCreateKernelsInProgram(arg1,arg2,arg3,arg4);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainKernel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_kernel arg1 = (cl_kernel) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_kernel *)&jarg1; 
  result = clRetainKernel(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseKernel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_kernel arg1 = (cl_kernel) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_kernel *)&jarg1; 
  result = clReleaseKernel(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clSetKernelArg(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  cl_kernel arg1 = (cl_kernel) 0 ;
  cl_uint arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  cl_int result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_kernel *)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  result = clSetKernelArg(arg1,arg2,arg3,(void const *)arg4);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetKernelInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_kernel arg1 = (cl_kernel) 0 ;
  cl_kernel_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_kernel_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_kernel *)&jarg1; 
  argp2 = *(cl_kernel_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_kernel_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetKernelInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetKernelWorkGroupInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  cl_kernel arg1 = (cl_kernel) 0 ;
  cl_device_id arg2 = (cl_device_id) 0 ;
  cl_kernel_work_group_info arg3 ;
  size_t arg4 ;
  void *arg5 = (void *) 0 ;
  size_t *arg6 = (size_t *) 0 ;
  cl_int result;
  cl_kernel_work_group_info *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_kernel *)&jarg1; 
  arg2 = *(cl_device_id *)&jarg2; 
  argp3 = *(cl_kernel_work_group_info **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_kernel_work_group_info");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (size_t)jarg4; 
  arg5 = *(void **)&jarg5; 
  arg6 = *(size_t **)&jarg6; 
  result = clGetKernelWorkGroupInfo(arg1,arg2,arg3,arg4,arg5,arg6);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clWaitForEvents(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  cl_uint arg1 ;
  cl_event *arg2 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(cl_uint **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(cl_event **)&jarg2; 
  result = clWaitForEvents(arg1,(void *const *)arg2);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetEventInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_event arg1 = (cl_event) 0 ;
  cl_event_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_event_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_event *)&jarg1; 
  argp2 = *(cl_event_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_event_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetEventInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clRetainEvent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_event arg1 = (cl_event) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_event *)&jarg1; 
  result = clRetainEvent(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clReleaseEvent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_event arg1 = (cl_event) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_event *)&jarg1; 
  result = clReleaseEvent(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clGetEventProfilingInfo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_event arg1 = (cl_event) 0 ;
  cl_profiling_info arg2 ;
  size_t arg3 ;
  void *arg4 = (void *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  cl_int result;
  cl_profiling_info *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_event *)&jarg1; 
  argp2 = *(cl_profiling_info **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_profiling_info");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  result = clGetEventProfilingInfo(arg1,arg2,arg3,arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clFlush(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  result = clFlush(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clFinish(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  result = clFinish(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueReadBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_bool arg3 ;
  size_t arg4 ;
  size_t arg5 ;
  void *arg6 = (void *) 0 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_bool *argp3 ;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = *(void **)&jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueReadBuffer(arg1,arg2,arg3,arg4,arg5,arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueWriteBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_bool arg3 ;
  size_t arg4 ;
  size_t arg5 ;
  void *arg6 = (void *) 0 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_bool *argp3 ;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = *(void **)&jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueWriteBuffer(arg1,arg2,arg3,arg4,arg5,(void const *)arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueCopyBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_mem arg3 = (cl_mem) 0 ;
  size_t arg4 ;
  size_t arg5 ;
  size_t arg6 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  arg3 = *(cl_mem *)&jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = (size_t)jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueCopyBuffer(arg1,arg2,arg3,arg4,arg5,arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueReadImage(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10, jlong jarg11) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_bool arg3 ;
  size_t **arg4 ;
  size_t **arg5 ;
  size_t arg6 ;
  size_t arg7 ;
  void *arg8 = (void *) 0 ;
  cl_uint arg9 ;
  cl_event *arg10 = (cl_event *) 0 ;
  cl_event *arg11 = (cl_event *) 0 ;
  cl_int result;
  cl_bool *argp3 ;
  cl_uint *argp9 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(size_t ***)&jarg4; 
  arg5 = *(size_t ***)&jarg5; 
  arg6 = (size_t)jarg6; 
  arg7 = (size_t)jarg7; 
  arg8 = *(void **)&jarg8; 
  argp9 = *(cl_uint **)&jarg9; 
  if (!argp9) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg9 = *argp9; 
  arg10 = *(cl_event **)&jarg10; 
  arg11 = *(cl_event **)&jarg11; 
  result = clEnqueueReadImage(arg1,arg2,arg3,(size_t const *(*))arg4,(size_t const *(*))arg5,arg6,arg7,arg8,arg9,(void *const *)arg10,arg11);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueWriteImage(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10, jlong jarg11) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_bool arg3 ;
  size_t **arg4 ;
  size_t **arg5 ;
  size_t arg6 ;
  size_t arg7 ;
  void *arg8 = (void *) 0 ;
  cl_uint arg9 ;
  cl_event *arg10 = (cl_event *) 0 ;
  cl_event *arg11 = (cl_event *) 0 ;
  cl_int result;
  cl_bool *argp3 ;
  cl_uint *argp9 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(size_t ***)&jarg4; 
  arg5 = *(size_t ***)&jarg5; 
  arg6 = (size_t)jarg6; 
  arg7 = (size_t)jarg7; 
  arg8 = *(void **)&jarg8; 
  argp9 = *(cl_uint **)&jarg9; 
  if (!argp9) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg9 = *argp9; 
  arg10 = *(cl_event **)&jarg10; 
  arg11 = *(cl_event **)&jarg11; 
  result = clEnqueueWriteImage(arg1,arg2,arg3,(size_t const *(*))arg4,(size_t const *(*))arg5,arg6,arg7,(void const *)arg8,arg9,(void *const *)arg10,arg11);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueCopyImage(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_mem arg3 = (cl_mem) 0 ;
  size_t **arg4 ;
  size_t **arg5 ;
  size_t **arg6 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  arg3 = *(cl_mem *)&jarg3; 
  arg4 = *(size_t ***)&jarg4; 
  arg5 = *(size_t ***)&jarg5; 
  arg6 = *(size_t ***)&jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueCopyImage(arg1,arg2,arg3,(size_t const *(*))arg4,(size_t const *(*))arg5,(size_t const *(*))arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueCopyImageToBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_mem arg3 = (cl_mem) 0 ;
  size_t **arg4 ;
  size_t **arg5 ;
  size_t arg6 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  arg3 = *(cl_mem *)&jarg3; 
  arg4 = *(size_t ***)&jarg4; 
  arg5 = *(size_t ***)&jarg5; 
  arg6 = (size_t)jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueCopyImageToBuffer(arg1,arg2,arg3,(size_t const *(*))arg4,(size_t const *(*))arg5,arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueCopyBufferToImage(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_mem arg3 = (cl_mem) 0 ;
  size_t arg4 ;
  size_t **arg5 ;
  size_t **arg6 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  arg3 = *(cl_mem *)&jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = *(size_t ***)&jarg5; 
  arg6 = *(size_t ***)&jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueCopyBufferToImage(arg1,arg2,arg3,arg4,(size_t const *(*))arg5,(size_t const *(*))arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueMapBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_bool arg3 ;
  cl_map_flags arg4 ;
  size_t arg5 ;
  size_t arg6 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int *arg10 = (cl_int *) 0 ;
  void *result = 0 ;
  cl_bool *argp3 ;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (cl_map_flags)jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = (size_t)jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  arg10 = *(cl_int **)&jarg10; 
  result = (void *)clEnqueueMapBuffer(arg1,arg2,arg3,arg4,arg5,arg6,arg7,(void *const *)arg8,arg9,arg10);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueMapImage(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10, jlong jarg11, jlong jarg12) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  cl_bool arg3 ;
  cl_map_flags arg4 ;
  size_t **arg5 ;
  size_t **arg6 ;
  size_t *arg7 = (size_t *) 0 ;
  size_t *arg8 = (size_t *) 0 ;
  cl_uint arg9 ;
  cl_event *arg10 = (cl_event *) 0 ;
  cl_event *arg11 = (cl_event *) 0 ;
  cl_int *arg12 = (cl_int *) 0 ;
  void *result = 0 ;
  cl_bool *argp3 ;
  cl_uint *argp9 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  argp3 = *(cl_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_bool");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (cl_map_flags)jarg4; 
  arg5 = *(size_t ***)&jarg5; 
  arg6 = *(size_t ***)&jarg6; 
  arg7 = *(size_t **)&jarg7; 
  arg8 = *(size_t **)&jarg8; 
  argp9 = *(cl_uint **)&jarg9; 
  if (!argp9) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg9 = *argp9; 
  arg10 = *(cl_event **)&jarg10; 
  arg11 = *(cl_event **)&jarg11; 
  arg12 = *(cl_int **)&jarg12; 
  result = (void *)clEnqueueMapImage(arg1,arg2,arg3,arg4,(size_t const *(*))arg5,(size_t const *(*))arg6,arg7,arg8,arg9,(void *const *)arg10,arg11,arg12);
  *(void **)&jresult = result; 
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueUnmapMemObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_mem arg2 = (cl_mem) 0 ;
  void *arg3 = (void *) 0 ;
  cl_uint arg4 ;
  cl_event *arg5 = (cl_event *) 0 ;
  cl_event *arg6 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_mem *)&jarg2; 
  arg3 = *(void **)&jarg3; 
  argp4 = *(cl_uint **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(cl_event **)&jarg5; 
  arg6 = *(cl_event **)&jarg6; 
  result = clEnqueueUnmapMemObject(arg1,arg2,arg3,arg4,(void *const *)arg5,arg6);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueNDRangeKernel(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_kernel arg2 = (cl_kernel) 0 ;
  cl_uint arg3 ;
  size_t *arg4 = (size_t *) 0 ;
  size_t *arg5 = (size_t *) 0 ;
  size_t *arg6 = (size_t *) 0 ;
  cl_uint arg7 ;
  cl_event *arg8 = (cl_event *) 0 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp3 ;
  cl_uint *argp7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_kernel *)&jarg2; 
  argp3 = *(cl_uint **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(size_t **)&jarg4; 
  arg5 = *(size_t **)&jarg5; 
  arg6 = *(size_t **)&jarg6; 
  argp7 = *(cl_uint **)&jarg7; 
  if (!argp7) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg7 = *argp7; 
  arg8 = *(cl_event **)&jarg8; 
  arg9 = *(cl_event **)&jarg9; 
  result = clEnqueueNDRangeKernel(arg1,arg2,arg3,(size_t const *)arg4,(size_t const *)arg5,(size_t const *)arg6,arg7,(void *const *)arg8,arg9);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueTask(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_kernel arg2 = (cl_kernel) 0 ;
  cl_uint arg3 ;
  cl_event *arg4 = (cl_event *) 0 ;
  cl_event *arg5 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_kernel *)&jarg2; 
  argp3 = *(cl_uint **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(cl_event **)&jarg4; 
  arg5 = *(cl_event **)&jarg5; 
  result = clEnqueueTask(arg1,arg2,arg3,(void *const *)arg4,arg5);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueNativeKernel(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  void (*arg2)(void *) = (void (*)(void *)) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  cl_uint arg5 ;
  cl_mem *arg6 = (cl_mem *) 0 ;
  void **arg7 = (void **) 0 ;
  cl_uint arg8 ;
  cl_event *arg9 = (cl_event *) 0 ;
  cl_event *arg10 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp5 ;
  cl_uint *argp8 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(void (**)(void *))&jarg2; 
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  argp5 = *(cl_uint **)&jarg5; 
  if (!argp5) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg5 = *argp5; 
  arg6 = *(cl_mem **)&jarg6; 
  arg7 = *(void ***)&jarg7; 
  argp8 = *(cl_uint **)&jarg8; 
  if (!argp8) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg8 = *argp8; 
  arg9 = *(cl_event **)&jarg9; 
  arg10 = *(cl_event **)&jarg10; 
  result = clEnqueueNativeKernel(arg1,arg2,arg3,arg4,arg5,(void *const *)arg6,(void const **)arg7,arg8,(void *const *)arg9,arg10);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueMarker(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_event *arg2 = (cl_event *) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  arg2 = *(cl_event **)&jarg2; 
  result = clEnqueueMarker(arg1,arg2);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueWaitForEvents(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_uint arg2 ;
  cl_event *arg3 = (cl_event *) 0 ;
  cl_int result;
  cl_uint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  argp2 = *(cl_uint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null cl_uint");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(cl_event **)&jarg3; 
  result = clEnqueueWaitForEvents(arg1,arg2,(void *const *)arg3);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_opencl_RawOpenCLJNI_clEnqueueBarrier(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  cl_command_queue arg1 = (cl_command_queue) 0 ;
  cl_int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(cl_command_queue *)&jarg1; 
  result = clEnqueueBarrier(arg1);
  {
    cl_int * resultptr = (cl_int *) malloc(sizeof(cl_int));
    memmove(resultptr, &result, sizeof(cl_int));
    *(cl_int **)&jresult = resultptr;
  }
  return jresult;
}


#ifdef __cplusplus
}
#endif

