/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_opencl_CLProgram */

#ifndef _Included_javax_opencl_CLProgram
#define _Included_javax_opencl_CLProgram
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
