all2:
	cd makeDivDev;	make

	cd numcellVStime;	make

	cd numcontactVStime;	make

	cd numcontactVSdurcontact;	make

	cd travelDist;	make

all:
	pslatex assembly.tex
#	dvips assembly.dvi
	dvipdf assembly.dvi
