/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package qhullj;

public class Qhullj {
  public static void qh_init_B(SWIGTYPE_p_coordT points, int numpoints, int dim, long ismalloc) {
    QhulljJNI.qh_init_B(SWIGTYPE_p_coordT.getCPtr(points), numpoints, dim, ismalloc);
  }

}
