/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package qhullj;

class QhulljJNI {
  public final static native void qh_init_B(long jarg1, int jarg2, int jarg3, long jarg4);
}
