.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "ENDROV" "1" "December 20, 2008" "Johan Henriksson" ""
.SH "NAME"
.LP 
endrov \- A modular framework for among other things, image processing and analysis.
.SH "SYNTAX"
.LP 
endrov [\fIoption\fP] <\fIfilename\fP>
.br 
endrov [\-i image] [\-b|\-m] [arg1 ... argN]
.SH "DESCRIPTION"
.LP 
\fBEndrov\fP is a modular framework for life science imaging developed at Karolinska Institutet.
The emphasis is on extensibility in form of plugins, scripts and flows.
It was developed with all level of users in mind, from biologists with little
computer experience to expert developers.
.SH "OPTIONS"
.LP 
.TP 
\fB\--cp\fR <\fCLASSPATH\fP>\fR
Add additional libraries to the classpath.
.TP 
\fB\-o\fR
Open images in existing ImageJ panel if one exists.
.TP 
\fB\-p\fR <\fIN\fP>
Open images in existing ImageJ panel number <N>.
.TP 
\fB\-x\fR <\fIMB\fP>   
Set available memory.
.TP 
\fB\-c\fR
Enable plugin compilation within imagej.
.TP 
\fB\-v\fR
Be verbose (vv or vvv increases verbosity).
.TP 
\fB\-e\fR \fIMacro Code\fP
Execute macro code.
.TP 
\fB\-r\fR \fIMenu Command\fP
Run menu command.
Quotation marks are required around commands including spaces
Commands can be sent to open ImageJ panels with the \-p option.
.TP 
\fB\-b\fR \fImacro\fP
Run macro without graphics window.
.TP 
\fB\-m\fR \fImacro\fP
Run macro, image will be opened before macro is run all following arguments are passed to macro.
.SH "FILES"
.LP 
Most IMAGEJ add\-on are taken from $HOME/.imagej.  The  system  wide
 equivalent is in /usr/share/imagej/
.TP 
.B \ HOME/.imagej/plugins/,
you can find and put new plugins here
.TP 
.B \ HOME/.imagej/macros/,
you can find and put new macros here
.TP 
.B \ HOME/.imagej/luts/,
you can find and put new look up tables here

.SH "EXAMPLES"
.LP 
For compiling plugins:
.LP 
imagej \-c
.SH "SEE ALSO"
.\"/.BR bar (1),
.\"/.BR baz (1).
.br 
The program is fully documented at 
http://www.endrov.net
.SH "AUTHOR"
.LP 
Endrov was originally written by Johan Henriksson <mahogny@areta.org>
.PP 
This manual page, the wrapper and packaging was done by Johan Henriksson, for the Debian project.
